default:
	@echo "There's s a section 'update' that downloads 'pacapt' from github and"
	@echo "saves the output to './files/default/pacman'. To continue, please type"
	@echo "    make update"

update:
	@echo ":: Downloading pacapt from github"
	@cd files/default && wget https://github.com/icy/pacapt/raw/master/pacman -O pacman
	@echo ":: Done. File saved in ./files/default/pacman"
